### ISSUE TITLE
TODO's - 2018/09/13

### ISSUE THREAD

**Issue by DanielSchuette** [LienDNguyen/calcium_imaging#1]
Things that a currently on our TODO list:

analysis notebook '20180913_calcium_imaging.ipynb':

- [x] Plot separate graphs of different groups on the same plot  @LienDNguyen 
- [ ] Calculate rate of rise @DanielSchuette
- [x] Combine data from slides of the same cell type @LienDNguyen
- [x] Areas under the curve @LienDNguyen
- [ ] Statistical analysis @DanielSchuette
- [x] Re-factor EDA code into functions @LienDNguyen

**Comment by LienDNguyen** [comment]
I'm taking a break!

**Comment by DanielSchuette** [comment]
I updated the TODO's. We should re-factor the exploratory data analysis code snippets into functions to increase re-usability!
